name: 'Builds Static website & hosts on https://qcr.github.io'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout site code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        env:
          cache-name: node
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          npm install
      - name: Build
        run: |
          git fetch --all
          REPO_CACHE='.repo_cache' npm run build
      - name: Push result to gh_pages branch
        run: |
          cp -r .next-out/ ../
          git fetch --all
          git checkout -f gh_pages
          git reset --hard build_root
          git clean -d -x -f
          rm -rf .repo_cache
          cp -r ../.next-out/* .
          cp ../.next-out/.repo* .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generated from contents of master commit: $(git rev-parse --short "$GITHUB_SHA")"
          git push -f
