name: 'Builds Static website & hosts on https://qcr.github.io'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout site code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
