name: 'Receives a remote update payload, and requests a rebuild'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name given to your content in cards and page titles'
        required: true
      id:
        description: 'ID to be used throughout site, including in URL'
        required: false
      content:
        description: 'Path of file to render for page content'
        required: false
      image:
        description: 'Path of image to use as the feature image in cards'
        required: false
      image_position:
        description: "Value for CSS 'background-position' of feature image"
        required: false

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout site code
        uses: actions/checkout@v2
      - name: Add payload to registered remote data
        run: |
          echo "TESTING:"
          echo "Hello ${{ toJson(github) }}"
