name: 'Receives a remote update payload, and requests a rebuild'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name given to your content in cards and page titles'
        required: true
      url:
        description: 'URL of requesting repository'
        required: true
      id:
        description: 'ID to be used throughout site, including in URL'
        required: false
      content:
        description: 'Path of file to render for page content'
        required: false
      image:
        description: 'Path of image to use as the feature image in cards'
        required: false
      image_position:
        description: "Value for CSS 'background-position' of feature image"
        required: false

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout site code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        env:
          cache-name: node
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install dependencies
        run: |
          npm install
      - name: Debug
        run: |
          echo "CD:"
          ls -al .
          echo "~.npm:"
          ls -al ~/.npm
      - name: Add a file corresponding to the payload (also check for errors)
        run: |
          echo "Adding file"
      - name: Create a new commit, only if it is necessary
        run: |
          echo "Creating a new commit if necessary"
      - name: Request a rebuild if required
        run: |
          echo "Rebuilding if necessary"
